@startuml Exporter
group 批处理
:File_Input;
split
:shell;
split again
:bat;
endsplit
endgroup
group 转换至FBXSDK可读
split
:fbx/3ds/obj/dae/dxf;
split again
:ply/stl/x3d/wrl/abc/svg;
:blend;
:Blender工具;
split again
:ma/mb;
:Maya工具;
split again
:max/MAX;
:3dsMax工具;
endsplit
endgroup
group FBX解析
split
:Animation;
split again
:Node;
split again
:BoundingBox;
split again
:Camera;
split again
:Light;
split again
:Material;
split again
:Mesh;
split again
:Morph;
split again
:Scene;
split again
:Skin;
endsplit
group 3rdParty
split
:FBXSDK2017处理FBX;
split again
:FlatBuffer序列化二进制规范;
split again
:FreeImage处理图像;
endsplit
endgroup
endgroup
:MD5加密;
group fbs_output
split
:model.fbs;
split again
:anim.fbs;
split again
:image;
split again
:mat.fbx;
split again
:mapping.json;
split again
:config.json;
splitend
endgroup
@enduml