@startuml Creator
:ICreator;
floating note right: ICreator全局对象,包含所有变量和方法！！！！
split
:Animation;
split again
:Ar;
split again
:Audio;
split again
:Basic;
split again
:Camera;
split again
:Core;
split again
:Effect;
split again
:Light;
split again
:Loader;
split again
:Material;
split again
:Math;
split again
:Mesh;
split again
:Misc;
split again
:Node;
split again
:Particle;
split again
:PassQueue;
split again
:ShaderChunks;
split again
:ShaderLibrary;
split again
:Skeleton;
split again
:Texture;
endsplit
@enduml