@startuml Loader
start
:osgb倾斜摄影数据;
note right 
Open Scene Gragh格式的二进制格式即OSGB
osg下只能通过外部储存纹理, osgb则直接嵌入了纹理数据
文件由XML结构描述文件+众多osgb模型数据组成
endnote
group 外部处理
switch(osgb转3DTiles)
case()
#SkyBlue:Github工具;
case()
:CesiumIon官方平台转换器;
case()
:Cesiumlab;
endswitch
endgroup
:得到3DTiles文件;
note right
文件由主tileset.json文件+众多b3dm模型数据和子tileset.json文件组成
=================================================================
b3dm/Binary3DModel描述独立的3D模型, 包含相关的纹理, 材质, LOD等信息
i3dm/Instaced3DModel描述共享的基础3D模型, 和多个实例的位置, 方向, 缩放比例等
endnote
:3DTilesLoader;
note right
读取tileset.json生成对应的js对象
endnote
group LOD逻辑
:读取tiles中的geometricError;
:计算相机距离模型BV的最近距离和倾角;
if(用SSE公式计算当前GE于预设值进行比较;
) then (<小于)
:满足精度要求,
将tile加入requestlist;
else (>大于)
:加载更深层瓦片并重复计算
直到SSE结果小于预设GE
将tile加入requestlist;
endif
:得到请求队列Request_tiles[];
endgroup
:TileLoader;
note right
将b3dm转化成glTF格式
endnote
:渲染glTF队列;
end

start
fork
:glTFLoader;
note right
读glTF到转换器格式
正常渲染Mesh和纹理
endnote
fork again
:LOD;
fork again
:3DTilesLoader;
floating note right
Cesium中已有
endnote
fork again
:JsonLoader;
end fork
end
@enduml