@startuml glTFParse
start
:全Loader异步执行//Promise.All确认异步加载情况;
Group LoadScene
split
:Scene下所有节点的ID;
split again
:通过ID映射读取对应节点内的完整信息;
endsplit
group LoadNodes
split
:遍历每个节点调用单节点解析函数;
split again
:为每个节点添加孩子信息;
endsplit
group LoadNode
split
:解包基本数据TRS,name,Matrix;
split again
:实例扩展,关节扩展;
split again
:解析网格片元信息,储存权重;
endsplit
group LoadPrimitive
split
group LoadMaterial
split
:镜面光泽||金属粗糙;
split again
:环境光||法线||遮蔽||自发光;
endsplit  
group LoadTexture
:TextureLoader;
endgroup
endgroup
split again
:Draco扩展;
split again
:顶点属性;
group LoadSemanticInfo
:解析属性中的语义;
group LoadAttribute
:解析属性,包含Accessor信息;
:VertexBufferLoader;
endgroup
endgroup
split again
:解析Morph;
split again
group LoadIndices
:IndexBufferLoader;
endgroup
split again
:解析结构化数据等;
endsplit
endgroup
endgroup
endgroup
endgroup
stop
@enduml